window.RWBY_DEFAULT_SHOP = [
  { category:'Dust — Crystals', rarity:'Common', name:'Fire Dust Crystal', price:1200, desc:'Refined red crystal. Ignites on impact or channels through a weapon. SDC grade, post-embargo pricing.' },
  { category:'Dust — Crystals', rarity:'Common', name:'Ice Dust Crystal', price:900, desc:'Pale blue crystal. Freezes targets and surfaces, forms barriers of ice.' },
  { category:'Dust — Crystals', rarity:'Common', name:'Lightning Dust Crystal', price:850, desc:'Yellow crystal crackling with charge. Arcs between conductive targets.' },
  { category:'Dust — Crystals', rarity:'Common', name:'Wind Dust Crystal', price:730, desc:'Green crystal. Releases concussive gusts, propels gliding and leaping.' },
  { category:'Dust — Crystals', rarity:'Common', name:'Earth Dust Crystal', price:600, desc:'Brown crystal. Raises stone, hardens ground, shapes cover.' },
  { category:'Dust — Crystals', rarity:'Rare', name:'Gravity Dust Crystal', price:14000, desc:'Rare violet crystal. Alters local gravity for floating platforms or crushing slams. Severe shortage since the rail line attacks.' },
  { category:'Dust — Crystals', rarity:'Rare', name:'Hard-Light Dust Crystal', price:16500, desc:'Rare prismatic crystal. Projects solid-light constructs and shields. Atlas-restricted, black-market priced.' },

  { category:'Dust — Vials & Powder', rarity:'Common', name:'Fire Dust Vial (powdered)', price:180, desc:'Loose red Dust for cartridge loading or pouches. Cheaper per use than crystal, less stable.' },
  { category:'Dust — Vials & Powder', rarity:'Common', name:'Ice Dust Vial (powdered)', price:180, desc:'Loose blue Dust. Common ammunition infusion.' },
  { category:'Dust — Vials & Powder', rarity:'Common', name:'Lightning Dust Vial (powdered)', price:190, desc:'Loose yellow Dust. Standard for ranged weapon charging.' },
  { category:'Dust — Vials & Powder', rarity:'Common', name:'Wind Dust Vial (powdered)', price:170, desc:'Loose green Dust. Mobility and knockback rounds.' },
  { category:'Dust — Vials & Powder', rarity:'Common', name:'Earth Dust Vial (powdered)', price:160, desc:'Loose brown Dust. Defensive and terrain rounds.' },
  { category:'Dust — Vials & Powder', rarity:'Rare', name:'Gravity Dust Vial (powdered)', price:520, desc:'Loose violet Dust. Scarce; rationed by most reputable shops.' },
  { category:'Dust — Vials & Powder', rarity:'Common', name:'Mixed Dust Pouch (assorted)', price:220, desc:'A pouch of mismatched powdered Dust. Unreliable potency, budget option.' },

  { category:'Dust — Ammunition', rarity:'Common', name:'Dust Cartridges, Standard (×30)', price:120, desc:'Pre-loaded rounds infused with elemental Dust. Specify element on purchase.' },
  { category:'Dust — Ammunition', rarity:'Common', name:'Dust Cartridges, Heavy (×15)', price:160, desc:'High-caliber Dust rounds for cannon-class weapons.' },
  { category:'Dust — Ammunition', rarity:'Common', name:'Dust Shells, Shotgun (×20)', price:140, desc:'Scattershot Dust shells. Popular for melee-shift weapons.' },
  { category:'Dust — Ammunition', rarity:'Common', name:'Dust Rounds, Sniper (×10)', price:200, desc:'Precision-cut Dust rounds with stabilized burn.' },

  { category:'Weapons — Melee', rarity:'Common', name:'Combat Knife', price:80, desc:'1d4 piercing/slashing. Light, concealable, throwable.' },
  { category:'Weapons — Melee', rarity:'Common', name:'Short Sword', price:180, desc:'1d6 slashing. Reliable Huntsman trainee sidearm.' },
  { category:'Weapons — Melee', rarity:'Common', name:'Longsword', price:300, desc:'1d8 slashing, two-handed 1d10. Standard versatile blade.' },
  { category:'Weapons — Melee', rarity:'Common', name:'Greatsword', price:500, desc:'2d6 slashing, heavy, two-handed. Favored by power fighters.' },
  { category:'Weapons — Melee', rarity:'Common', name:'War Axe', price:340, desc:'1d8 slashing, brutal on a critical hit.' },
  { category:'Weapons — Melee', rarity:'Common', name:'Battle Spear', price:260, desc:'1d8 piercing, reach. Keeps Grimm at distance.' },
  { category:'Weapons — Melee', rarity:'Common', name:'War Hammer', price:420, desc:'2d6 bludgeoning, heavy. Stuns and shatters guard.' },
  { category:'Weapons — Melee', rarity:'Common', name:'Twin Daggers (pair)', price:240, desc:'1d4 each, light, dual-wield. Quick Semblance-paired strikes.' },
  { category:'Weapons — Melee', rarity:'Common', name:'Quarterstaff', price:60, desc:'1d6 bludgeoning, versatile 1d8. Cheap, dependable.' },

  { category:'Weapons — Ranged', rarity:'Common', name:'Light Pistol', price:280, desc:'1d8 piercing, 30/90 ft. Sidearm; chambers Dust cartridges.' },
  { category:'Weapons — Ranged', rarity:'Common', name:'Hunting Rifle', price:520, desc:'1d10 piercing, 80/240 ft. Bread-and-butter Huntsman ranged arm.' },
  { category:'Weapons — Ranged', rarity:'Common', name:'Combat Shotgun', price:480, desc:'2d6 at close range, 30/90 ft. Pairs with shift-weapons.' },
  { category:'Weapons — Ranged', rarity:'Uncommon', name:'Sniper Rifle', price:900, desc:'2d10 piercing, 120/480 ft. High cost, high reach.' },
  { category:'Weapons — Ranged', rarity:'Common', name:'Recurve Bow', price:120, desc:'1d8 piercing, 150/600 ft. Silent; takes Dust-tipped arrows.' },
  { category:'Weapons — Ranged', rarity:'Common', name:'Hand Crossbow', price:160, desc:'1d6 piercing, light, 30/120 ft.' },

  { category:'Weapons — Mecha-Shift', rarity:'Uncommon', name:'Mecha-Shift Frame (blank)', price:1200, desc:'A modular weapon chassis that transforms between two configured forms. Requires a smith to fit your blueprint.' },
  { category:'Weapons — Mecha-Shift', rarity:'Uncommon', name:'Transformation Smithing (service)', price:850, desc:'A weaponsmith adds a second mecha-shift form to a weapon you already own.' },
  { category:'Weapons — Mecha-Shift', rarity:'Uncommon', name:'Dust-Channeling Refit (service)', price:600, desc:'Upgrades a weapon to channel loaded Dust through its strikes or shots.' },

  { category:'Armor', rarity:'Common', name:'Reinforced Clothing', price:120, desc:'+1 AC. Light huntsman garb with woven plating. No stealth penalty.' },
  { category:'Armor', rarity:'Common', name:'Leather Combat Gear', price:200, desc:'Light armor, AC 11 + DEX. Flexible and quiet.' },
  { category:'Armor', rarity:'Common', name:'Studded Huntsman Vest', price:450, desc:'Light armor, AC 12 + DEX. Standard academy issue.' },
  { category:'Armor', rarity:'Common', name:'Chain Shirt', price:500, desc:'Medium armor, AC 13 + DEX (max 2). Worn under clothing.' },
  { category:'Armor', rarity:'Uncommon', name:'Reinforced Breastplate', price:800, desc:'Medium armor, AC 14 + DEX (max 2). Atlas-forged steel.' },
  { category:'Armor', rarity:'Rare', name:'Half-Plate', price:1500, desc:'Medium armor, AC 15 + DEX (max 2). Stealth disadvantage.' },
  { category:'Armor', rarity:'Rare', name:'Full Plate', price:3000, desc:'Heavy armor, AC 18. Stealth disadvantage, STR 15 required.' },
  { category:'Armor', rarity:'Common', name:'Combat Shield', price:150, desc:'+2 AC. Some collapse into a gauntlet for shift-weapon users.' },
  { category:'Armor', rarity:'Uncommon', name:'Dust-Weave Cloak', price:18000, desc:'Resistant to one chosen Dust element; faint shimmer when triggered.' },

  { category:'Tools & Tech', rarity:'Common', name:'Scroll (standard)', price:400, desc:'The handheld communication and info device of Remnant. Calls, maps, Aura readouts, transformation triggers. Networked to the CCT.' },
  { category:'Tools & Tech', rarity:'Uncommon', name:'Scroll (military-grade)', price:1100, desc:'Hardened Atlas Scroll with encrypted comms, deployable holo-display, and Aura-scanner ports.' },
  { category:'Tools & Tech', rarity:'Common', name:'First-Aid Med Kit', price:90, desc:'Bandages, salves, and a stim shot. Stabilizes a downed ally or restores a short rest of HP.' },
  { category:'Tools & Tech', rarity:'Common', name:'Field Surgery Kit', price:260, desc:'Advanced kit; grants advantage on Medicine checks and treats serious wounds.' },
  { category:'Tools & Tech', rarity:'Common', name:'Aura Stabilizer (single-use)', price:3200, desc:'Injector that jump-starts a depleted Aura, restoring a small reserve once per use.' },
  { category:'Tools & Tech', rarity:'Common', name:'Dust Refining Kit', price:3800, desc:'Portable tools to refine raw Dust into usable powder or recharge cartridges.' },
  { category:'Tools & Tech', rarity:'Common', name:'Grappling Hook & Line', price:75, desc:'50 ft line with a Dust-assisted retract. Climb, swing, or pull.' },
  { category:'Tools & Tech', rarity:'Common', name:'Climbing Kit', price:50, desc:'Pitons, harness, and rope for vertical terrain.' },
  { category:'Tools & Tech', rarity:'Common', name:'Survival Pack', price:110, desc:'Bedroll, rations (7 days), tinderbox, mess kit, waterskin, rope.' },
  { category:'Tools & Tech', rarity:'Common', name:'Binoculars (Dust-optic)', price:140, desc:'Long-range optics with low-light Dust enhancement.' },
  { category:'Tools & Tech', rarity:'Common', name:'Holo-Map Projector', price:230, desc:'Projects terrain and tactical overlays from Scroll data.' },
  { category:'Tools & Tech', rarity:'Common', name:'Lockpick Set', price:60, desc:'Quality picks for mechanical and simple electronic locks.' },
  { category:'Tools & Tech', rarity:'Common', name:'Flare Launcher (×6 flares)', price:85, desc:'Signal flares for distress, marking, or a brief blinding flash.' },
  { category:'Tools & Tech', rarity:'Rare', name:'Portable Shield Generator', price:13000, desc:'Deploys a temporary Hard-Light barrier. Atlas tech, limited charges.' },

  { category:'Consumables', rarity:'Common', name:'Healing Tonic', price:1300, desc:'Restores a modest amount of HP when drunk. Bitter, fast-acting.' },
  { category:'Consumables', rarity:'Common', name:'Stim Shot', price:1800, desc:'Temporary surge of speed and resilience for one encounter.' },
  { category:'Consumables', rarity:'Common', name:'Antitoxin Vial', price:6000, desc:'Advantage on saves against poison for one hour.' },
  { category:'Consumables', rarity:'Common', name:'Smoke Pellets (×5)', price:70, desc:'Throwable smoke for cover or escape.' },
  { category:'Consumables', rarity:'Common', name:'Ration Bars (×7)', price:35, desc:'A week of compact field rations.' },
  { category:'Consumables', rarity:'Common', name:'Aura Energy Drink', price:45000, desc:'Minor Aura regen over a short rest. Tastes like burnt sugar.' },

  { category:'Services', rarity:'Common', name:'Weapon Maintenance', price:500, desc:'A smith cleans, sharpens, and tunes one weapon to peak condition.' },
  { category:'Services', rarity:'Common', name:'Armor Repair', price:8000, desc:'Restores damaged armor to full protection.' },
  { category:'Services', rarity:'Common', name:'Dust Recharge (per weapon)', price:9000, desc:'Tops off a weapon\u2019s built-in Dust reservoir.' },
  { category:'Services', rarity:'Common', name:'Bullhead Transport (one-way)', price:3000, desc:'Airship passage to a kingdom or frontier outpost.' },
  { category:'Services', rarity:'Common', name:'Inn Stay (per night)', price:250, desc:'A bed, a hot meal, and a locked door between you and the night.' },
{ category:'Weapons — Melee', rarity:'Uncommon', name:'Chain Scythe', price:780, desc:'1d8 slashing with reach. Collapsible segmented haft; favored by highly mobile Huntsmen.' },
  { category:'Weapons — Melee', rarity:'Uncommon', name:'Dust Edge Saber', price:980, desc:'1d8 slashing. Replaceable Dust channel along the blade can add elemental effects when loaded.' },
  { category:'Weapons — Melee', rarity:'Uncommon', name:'Twin Tonfa Blades', price:720, desc:'Paired defensive blades designed for close-range counters and fast follow-up strikes.' },
  { category:'Weapons — Melee', rarity:'Rare', name:'Vibro-Greatblade', price:4200, desc:'Heavy two-handed blade with a Dust-powered vibration core for breaking armor and Grimm plating.' },

  { category:'Weapons — Ranged', rarity:'Common', name:'Machine Pistol', price:440, desc:'Compact automatic sidearm. High fire rate, short effective range, accepts standard Dust cartridges.' },
  { category:'Weapons — Ranged', rarity:'Uncommon', name:'Burst Carbine', price:880, desc:'Reliable three-round-burst rifle for mid-range Huntsman engagements.' },
  { category:'Weapons — Ranged', rarity:'Uncommon', name:'Heavy Revolver', price:760, desc:'High-caliber sidearm with excellent stopping power. Common among independent Huntsmen.' },
  { category:'Weapons — Ranged', rarity:'Rare', name:'Dust Rail Rifle', price:6200, desc:'Atlas-pattern long rifle that accelerates Dust-infused slugs. Extremely accurate and expensive to maintain.' },
  { category:'Weapons — Ranged', rarity:'Uncommon', name:'Repeating Crossbow', price:620, desc:'Compact repeating bow with magazine-fed bolts; useful where gunfire would attract Grimm.' },

  { category:'Weapons — Mecha-Shift', rarity:'Rare', name:'Advanced Mecha-Shift Core', price:4800, desc:'Precision transformation core supporting three mechanical configurations instead of two.' },
  { category:'Weapons — Mecha-Shift', rarity:'Rare', name:'Integrated Grapple Module', price:2100, desc:'Weapon-mounted retractable grappling system for rapid traversal, pulls, and aerial repositioning.' },
  { category:'Weapons — Mecha-Shift', rarity:'Rare', name:'Recoil Mobility Refit', price:2700, desc:'Reinforces a ranged weapon so recoil can safely be used for movement and airborne direction changes.' },
  { category:'Weapons — Mecha-Shift', rarity:'Rare', name:'Hidden Weapon Conversion', price:3500, desc:'Converts one weapon form into a disguised civilian object or compact carry mode.' },

  { category:'Dust — Ammunition', rarity:'Common', name:'Fire Dust Magazine (×20)', price:220, desc:'Preloaded magazine of incendiary Dust rounds.' },
  { category:'Dust — Ammunition', rarity:'Common', name:'Ice Dust Magazine (×20)', price:220, desc:'Preloaded cryogenic Dust rounds that rapidly chill struck surfaces.' },
  { category:'Dust — Ammunition', rarity:'Common', name:'Lightning Dust Magazine (×20)', price:240, desc:'Electrified Dust rounds useful against machines and conductive targets.' },
  { category:'Dust — Ammunition', rarity:'Uncommon', name:'Gravity Dust Rounds (×10)', price:850, desc:'Specialized rounds that create brief localized gravity distortions on impact.' },
  { category:'Dust — Ammunition', rarity:'Rare', name:'Hard-Light Breach Rounds (×6)', price:1600, desc:'Atlas hard-light projectiles designed to punch through cover before destabilizing.' },
  { category:'Dust — Ammunition', rarity:'Uncommon', name:'Dust-Tipped Arrows (×12)', price:360, desc:'Choose Fire, Ice, Wind, Lightning, or Earth when purchased.' },

  { category:'Armor', rarity:'Uncommon', name:'Huntsman Longcoat', price:720, desc:'Reinforced coat with concealed plates and Dust-resistant lining. Built for mobility and weather protection.' },
  { category:'Armor', rarity:'Uncommon', name:'Faunus Mobility Harness', price:680, desc:'Flexible combat harness designed not to obstruct tails, ears, wings, horns, or other Faunus traits.' },
  { category:'Armor', rarity:'Uncommon', name:'Aura-Conductive Undersuit', price:2200, desc:'Special weave designed to distribute Aura reinforcement more evenly across the body.' },
  { category:'Armor', rarity:'Rare', name:'Atlas Tactical Exoskeleton', price:12500, desc:'Powered support frame for carrying heavy equipment and stabilizing recoil. Requires regular charging.' },
  { category:'Armor', rarity:'Rare', name:'Hard-Light Buckler', price:9800, desc:'Wrist-mounted projector forming a compact Hard-Light shield when activated.' },

  { category:'Tools & Tech', rarity:'Common', name:'Weapon Cleaning Kit', price:55, desc:'Brushes, solvents, oils, micro-tools and sharpening gear for field maintenance.' },
  { category:'Tools & Tech', rarity:'Common', name:'Portable CCT Relay', price:950, desc:'Short-range communication relay for maintaining team contact in weak-signal areas.' },
  { category:'Tools & Tech', rarity:'Uncommon', name:'Aura Scanner', price:1600, desc:'Handheld scanner that estimates Aura reserves and detects abrupt Aura fluctuations.' },
  { category:'Tools & Tech', rarity:'Uncommon', name:'Grimm Motion Sensor', price:1250, desc:'Deployable sensor tuned to large moving biological signatures and Grimm activity.' },
  { category:'Tools & Tech', rarity:'Uncommon', name:'Thermal Monocular', price:780, desc:'Low-light and heat-signature optic that clips to a visor or weapon rail.' },
  { category:'Tools & Tech', rarity:'Uncommon', name:'Encrypted Scroll Module', price:1450, desc:'Adds encrypted team channels and secure file storage to a standard Scroll.' },
  { category:'Tools & Tech', rarity:'Rare', name:'Portable Hard-Light Workbench', price:7600, desc:'Compact projection bench used for weaponsmithing, field repairs, and schematic work.' },
  { category:'Tools & Tech', rarity:'Rare', name:'Micro-Drone Scout', price:5800, desc:'Palm-sized reconnaissance drone with camera, microphone, and short-range Scroll link.' },
  { category:'Tools & Tech', rarity:'Rare', name:'Signal Jammer', price:5200, desc:'Short-range electronic jammer. Illegal in many civilian districts without authorization.' },

  { category:'Field Gear', rarity:'Common', name:'Huntsman Field Pack', price:180, desc:'Durable mission pack with reinforced straps, modular pouches, hydration bladder, and weapon attachment points.' },
  { category:'Field Gear', rarity:'Common', name:'Cold-Weather Kit', price:140, desc:'Insulated layers, thermal blanket, hand warmers, snow goggles and emergency heat packs.' },
  { category:'Field Gear', rarity:'Common', name:'Desert Survival Kit', price:160, desc:'Shade cloth, water purification tablets, cooling wrap, goggles and compact electrolyte packs.' },
  { category:'Field Gear', rarity:'Common', name:'Urban Infiltration Kit', price:220, desc:'Compact pry tools, glass cutter, cable launcher, blackout cloth and disposable disguises.' },
  { category:'Field Gear', rarity:'Uncommon', name:'Climbing Grapnel Launcher', price:520, desc:'Compressed-gas launcher with reinforced line for rapid rooftop or cliff access.' },
  { category:'Field Gear', rarity:'Uncommon', name:'Emergency Beacon', price:300, desc:'Long-range distress beacon with flashing locator and encoded Scroll identifier.' },
  { category:'Field Gear', rarity:'Uncommon', name:'Portable Tent — Huntsman Grade', price:360, desc:'Lightweight reinforced shelter resistant to severe weather and minor Grimm scratches.' },

  { category:'Consumables', rarity:'Common', name:'Combat Ration Pack', price:18, desc:'One day of high-calorie field food designed for Huntsmen on extended missions.' },
  { category:'Consumables', rarity:'Common', name:'Electrolyte Recovery Pack', price:35, desc:'Powdered hydration mix for recovery after long travel or combat.' },
  { category:'Consumables', rarity:'Common', name:'Burn Treatment Foam', price:90, desc:'Rapid-cooling medical foam for fire and Dust burns.' },
  { category:'Consumables', rarity:'Common', name:'Coagulant Spray', price:110, desc:'Emergency wound sealant used to control heavy bleeding until proper treatment is available.' },
  { category:'Consumables', rarity:'Uncommon', name:'Aura Recovery Ampoule', price:2400, desc:'Single-use stimulant formulated to improve Aura recovery during a rest. Overuse is discouraged.' },
  { category:'Consumables', rarity:'Uncommon', name:'Focus Suppressant', price:750, desc:'Short-term medication used by some Huntsmen to steady severe adrenaline shakes after combat.' },

  { category:'Academy & Training', rarity:'Common', name:'Beacon Training Pass', price:120, desc:'Access to academy sparring rooms, basic targets, and standard training equipment for one session.' },
  { category:'Academy & Training', rarity:'Common', name:'Dust Practice Pack', price:95, desc:'Low-yield training Dust cartridges intended for controlled practice.' },
  { category:'Academy & Training', rarity:'Uncommon', name:'Combat Simulation Session', price:350, desc:'One advanced training-room simulation with configurable Grimm and terrain scenarios.' },
  { category:'Academy & Training', rarity:'Uncommon', name:'Weaponsmith Consultation', price:260, desc:'One hour with a professional weaponsmith to review a weapon concept, fault, or upgrade path.' },
  { category:'Academy & Training', rarity:'Uncommon', name:'Semblance Control Session', price:400, desc:'Supervised session focused on control, efficiency, and safe limits rather than raw power.' },

  { category:'Travel & Vehicles', rarity:'Common', name:'Inter-City Rail Ticket', price:180, desc:'Standard civilian rail passage where service remains available.' },
  { category:'Travel & Vehicles', rarity:'Common', name:'Motorcycle Rental — 1 Day', price:420, desc:'Civilian motorcycle rental with basic insurance and fuel.' },
  { category:'Travel & Vehicles', rarity:'Uncommon', name:'Huntsman Bike Rental — 1 Day', price:750, desc:'Reinforced off-road motorcycle equipped for rough terrain and weapon storage.' },
  { category:'Travel & Vehicles', rarity:'Uncommon', name:'Bullhead Charter — Local', price:2200, desc:'Private Bullhead transport for a small team within the same kingdom.' },
  { category:'Travel & Vehicles', rarity:'Rare', name:'Bullhead Charter — Long Range', price:7800, desc:'Long-range charter with pilot, fuel, and limited cargo capacity.' },

  { category:'Services', rarity:'Uncommon', name:'Custom Weapon Engraving', price:280, desc:'Professional engraving, insignia work, team markings, or personalization.' },
  { category:'Services', rarity:'Uncommon', name:'Weapon Balance Tuning', price:650, desc:'Precision adjustment of grip, recoil, weight distribution, and transformation timing.' },
  { category:'Services', rarity:'Uncommon', name:'Scroll Data Recovery', price:900, desc:'Technical service attempting to recover damaged or deleted data from a Scroll.' },
  { category:'Services', rarity:'Rare', name:'Full Mecha-Shift Rebuild', price:7200, desc:'Complete overhaul of a damaged or outdated transforming weapon mechanism.' },

  { category:'Black Market', rarity:'Uncommon', name:'Unregistered Scroll', price:2300, desc:'A Scroll with falsified ownership records. Possession may be illegal depending on jurisdiction.' },
  { category:'Black Market', rarity:'Rare', name:'Atlas Access Spoofer', price:8400, desc:'Illegal device intended to imitate low-level Atlas credentials. Reliability is questionable.' },
  { category:'Black Market', rarity:'Rare', name:'Restricted Dust Case', price:12500, desc:'Military-grade sealed case containing assorted high-output Dust charges. Highly regulated.' },
  { category:'Black Market', rarity:'Rare', name:'Prototype Aura Capacitor', price:18500, desc:'Experimental device intended to temporarily store Aura-derived energy. Unstable and unsupported.' },
{ category:'Dust — Blends', rarity:'Uncommon', name:'Steam Dust Cartridge', price:520, desc:'Fire and Water Dust blend that bursts into dense scalding steam. Useful for concealment and area denial.' },
  { category:'Dust — Blends', rarity:'Uncommon', name:'Magma Dust Cartridge', price:680, desc:'Fire and Earth Dust mixture that produces molten impact effects and persistent heat.' },
  { category:'Dust — Blends', rarity:'Uncommon', name:'Storm Dust Cartridge', price:720, desc:'Wind and Lightning blend creating violent electrical gusts and unstable arcs.' },
  { category:'Dust — Blends', rarity:'Uncommon', name:'Frost-Wind Cartridge', price:610, desc:'Ice and Wind blend used for freezing blasts, sleet bursts, and accelerated movement.' },
  { category:'Dust — Blends', rarity:'Rare', name:'Gravity-Ice Compression Cell', price:3200, desc:'Specialized blend that slows movement by combining localized gravity pressure with flash-freezing.' },
  { category:'Dust — Blends', rarity:'Rare', name:'Hard-Light Fire Cell', price:3800, desc:'Forms temporary hard-light structures that burn or detonate when destabilized.' },
  { category:'Dust — Blends', rarity:'Rare', name:'Lightning Gravity Pulse Cell', price:4100, desc:'Creates a short-range electromagnetic shock with a violent directional gravity tug.' },
  { category:'Dust — Blends', rarity:'Uncommon', name:'Earth-Ice Barrier Mix', price:590, desc:'Rapidly creates reinforced frozen stone cover. Popular with defensive Huntsmen.' },

  { category:'Weapon Mods', rarity:'Common', name:'Reinforced Weapon Grip', price:160, desc:'Improved grip material and ergonomic reshaping for better handling in rain, snow, or blood.' },
  { category:'Weapon Mods', rarity:'Common', name:'Extended Magazine Housing', price:280, desc:'Allows compatible firearms to accept higher-capacity magazines.' },
  { category:'Weapon Mods', rarity:'Common', name:'Recoil Compensator', price:330, desc:'Mechanical compensator that reduces muzzle rise and improves follow-up shot control.' },
  { category:'Weapon Mods', rarity:'Uncommon', name:'Dust Injection Chamber', price:1250, desc:'Adds a modular chamber allowing a weapon to channel bottled or powdered Dust.' },
  { category:'Weapon Mods', rarity:'Uncommon', name:'Quick-Transform Gearset', price:1900, desc:'Precision gears reduce the delay between Mecha-Shift weapon forms.' },
  { category:'Weapon Mods', rarity:'Uncommon', name:'Magnetic Weapon Retention', price:520, desc:'Magnetic holster and weapon mount system for rapid retrieval and secure aerial movement.' },
  { category:'Weapon Mods', rarity:'Uncommon', name:'Integrated Rangefinder', price:840, desc:'Compact digital rangefinder linked to a firearm sight or Scroll.' },
  { category:'Weapon Mods', rarity:'Uncommon', name:'Dust Venting System', price:980, desc:'Improves heat and pressure venting in Dust-powered weapons, reducing catastrophic overload risk.' },
  { category:'Weapon Mods', rarity:'Rare', name:'Hard-Light Edge Projector', price:6200, desc:'Projects a short hard-light extension along a compatible melee weapon.' },
  { category:'Weapon Mods', rarity:'Rare', name:'Aura-Responsive Trigger', price:7100, desc:'Experimental trigger assembly keyed to its owner’s Aura signature.' },
  { category:'Weapon Mods', rarity:'Rare', name:'Adaptive Mecha-Shift Frame', price:8900, desc:'Advanced modular frame allowing a weaponsmith to redesign one existing transformation mode.' },
  { category:'Weapon Mods', rarity:'Rare', name:'Gravity Recoil Assembly', price:9400, desc:'Uses Gravity Dust to redirect weapon recoil into controlled movement bursts.' },

  { category:'Weapon Parts', rarity:'Common', name:'Universal Huntsman Repair Parts', price:190, desc:'Springs, pins, bolts, cables, bearings and replacement hardware for field repairs.' },
  { category:'Weapon Parts', rarity:'Common', name:'Replacement Blade Segment', price:140, desc:'Standard high-carbon replacement section for segmented or transforming melee weapons.' },
  { category:'Weapon Parts', rarity:'Common', name:'Spare Firearm Barrel', price:320, desc:'Replacement barrel for common Huntsman-caliber firearms.' },
  { category:'Weapon Parts', rarity:'Uncommon', name:'Precision Transformation Servo', price:760, desc:'High-quality actuator used in reliable Mecha-Shift transformations.' },
  { category:'Weapon Parts', rarity:'Uncommon', name:'Dust-Resistant Internal Wiring', price:580, desc:'Insulated wiring designed for weapons that regularly channel elemental Dust.' },
  { category:'Weapon Parts', rarity:'Rare', name:'Atlas Military Servo Pack', price:2700, desc:'Military-grade servos salvaged or legally resold from Atlas hardware.' },

  { category:'Special Ammunition', rarity:'Common', name:'Armor-Piercing Rounds (×20)', price:310, desc:'Dense penetrator rounds intended for armor, reinforced Grimm plating, and light machinery.' },
  { category:'Special Ammunition', rarity:'Common', name:'Hollow-Point Rounds (×20)', price:240, desc:'Expanding ammunition designed for maximum soft-target damage.' },
  { category:'Special Ammunition', rarity:'Common', name:'Tracer Rounds (×20)', price:190, desc:'Visible flight-path ammunition useful for coordination and marking targets.' },
  { category:'Special Ammunition', rarity:'Uncommon', name:'Grimm-Breaker Slugs (×8)', price:720, desc:'Heavy shotgun slugs designed for thick bone plating and large Grimm.' },
  { category:'Special Ammunition', rarity:'Uncommon', name:'Net Cartridge (×4)', price:460, desc:'Compressed deployment cartridge that launches a reinforced capture net.' },
  { category:'Special Ammunition', rarity:'Uncommon', name:'Flashbang Shells (×6)', price:520, desc:'Non-lethal bright-light and concussion shells for breaching or crowd control.' },
  { category:'Special Ammunition', rarity:'Uncommon', name:'Smoke Shells (×6)', price:390, desc:'Dense smoke ammunition for obscuring sightlines without using Dust.' },
  { category:'Special Ammunition', rarity:'Rare', name:'Aura-Disruptor Test Rounds (×4)', price:4500, desc:'Experimental ammunition designed to create sudden Aura stress. Restricted prototype stock.' },

  { category:'Medical', rarity:'Common', name:'Compact First Aid Kit', price:120, desc:'Bandages, disinfectant, sutures, pain relief, gloves, and basic trauma supplies.' },
  { category:'Medical', rarity:'Common', name:'Trauma Kit', price:340, desc:'Advanced field medical supplies for severe wounds, fractures, and emergency stabilization.' },
  { category:'Medical', rarity:'Common', name:'Splint & Brace Set', price:80, desc:'Compact adjustable supports for fractures, sprains, and joint injuries.' },
  { category:'Medical', rarity:'Uncommon', name:'Portable Defibrillator', price:1300, desc:'Compact emergency defibrillator suitable for field teams and transport vehicles.' },
  { category:'Medical', rarity:'Uncommon', name:'Medical Scanner', price:1650, desc:'Portable diagnostic scanner for identifying internal injuries and monitoring vital signs.' },
  { category:'Medical', rarity:'Uncommon', name:'Aura-Burn Treatment Kit', price:890, desc:'Specialized cooling and recovery supplies for injuries involving extreme Aura exhaustion.' },
  { category:'Medical', rarity:'Rare', name:'Atlas Auto-Suture Unit', price:4200, desc:'Automated medical device capable of rapidly closing clean wounds in the field.' },
  { category:'Medical', rarity:'Rare', name:'Emergency Stasis Pod Rental', price:8500, desc:'Short-term rental of a portable Atlas medical stasis capsule for dangerous transport cases.' },

  { category:'Faunus Gear', rarity:'Common', name:'Faunus Ear Protection', price:75, desc:'Adjustable hearing protection designed for characters with sensitive animal ears.' },
  { category:'Faunus Gear', rarity:'Common', name:'Tail Armor Sleeve', price:130, desc:'Flexible protective sleeve for combat-capable tails without restricting movement.' },
  { category:'Faunus Gear', rarity:'Common', name:'Horn Guard Set', price:120, desc:'Protective caps and reinforcement mounts for Faunus horns or antlers.' },
  { category:'Faunus Gear', rarity:'Uncommon', name:'Wing-Friendly Combat Harness', price:850, desc:'Open-back armor harness designed for winged Faunus.' },
  { category:'Faunus Gear', rarity:'Uncommon', name:'Enhanced Scent Filter Mask', price:420, desc:'Reduces overwhelming chemical or biological smells for scent-sensitive Faunus.' },
  { category:'Faunus Gear', rarity:'Uncommon', name:'Low-Light Combat Visor', price:790, desc:'Visor designed to enhance rather than interfere with naturally strong Faunus night vision.' },
  { category:'Faunus Gear', rarity:'Uncommon', name:'Claw Reinforcement Bracers', price:680, desc:'Protects hands and supports Faunus with natural claws during close combat.' },
  { category:'Faunus Gear', rarity:'Rare', name:'Adaptive Faunus Armor Tailoring', price:3600, desc:'Custom armor redesign around unusual traits such as wings, tails, horns, scales, or digitigrade legs.' },

  { category:'Clothing & Disguises', rarity:'Common', name:'Beacon Academy Uniform', price:180, desc:'Standard academy uniform with school insignia and fitted jacket.' },
  { category:'Clothing & Disguises', rarity:'Common', name:'Huntsman Casual Wear Set', price:240, desc:'Durable civilian clothing with concealed pockets and reinforced seams.' },
  { category:'Clothing & Disguises', rarity:'Common', name:'Formal Huntsman Attire', price:520, desc:'Formal clothing suitable for galas, official meetings, and kingdom events.' },
  { category:'Clothing & Disguises', rarity:'Uncommon', name:'Urban Disguise Kit', price:390, desc:'Wigs, cosmetics, temporary hair dye, glasses, clothing accessories, and identity-cover props.' },
  { category:'Clothing & Disguises', rarity:'Uncommon', name:'White Fang Replica Mask', price:310, desc:'Commercial or black-market replica mask. Wearing one publicly may attract unwanted attention.' },
  { category:'Clothing & Disguises', rarity:'Uncommon', name:'Weatherproof Cloak', price:440, desc:'Long reinforced cloak with rain resistance, heat lining, and hidden storage.' },
  { category:'Clothing & Disguises', rarity:'Rare', name:'Active Camouflage Poncho', price:7600, desc:'Atlas-derived light-bending fabric that reduces visual detection while stationary.' },

  { category:'Scroll Upgrades', rarity:'Common', name:'Scroll Battery Upgrade', price:230, desc:'Higher-capacity battery module for extended field operations.' },
  { category:'Scroll Upgrades', rarity:'Common', name:'Rugged Scroll Case', price:90, desc:'Shockproof, water-resistant protective housing for a personal Scroll.' },
  { category:'Scroll Upgrades', rarity:'Uncommon', name:'Long-Range Antenna Module', price:740, desc:'Improves Scroll connectivity in remote terrain and damaged CCT coverage.' },
  { category:'Scroll Upgrades', rarity:'Uncommon', name:'Holographic Projector Upgrade', price:1150, desc:'Adds a brighter and larger projected display for maps, schematics, and briefings.' },
  { category:'Scroll Upgrades', rarity:'Uncommon', name:'Encrypted Team Network', price:1600, desc:'Secure tactical network package for a team of up to six registered Scrolls.' },
  { category:'Scroll Upgrades', rarity:'Rare', name:'Atlas Tactical Scroll', price:5800, desc:'Military-pattern Scroll with hardened casing, advanced sensors, and encrypted communications.' },
  { category:'Scroll Upgrades', rarity:'Rare', name:'Portable CCT Uplink', price:6900, desc:'Heavy backpack-mounted uplink capable of maintaining communications in degraded network zones.' },

  { category:'Recon & Surveillance', rarity:'Common', name:'Compact Binoculars', price:95, desc:'Durable field binoculars with range markings and low-light coating.' },
  { category:'Recon & Surveillance', rarity:'Common', name:'Audio Recorder', price:110, desc:'Small encrypted recorder for interviews, evidence, or mission logs.' },
  { category:'Recon & Surveillance', rarity:'Uncommon', name:'Remote Camera Pack (×4)', price:880, desc:'Four small wireless cameras capable of streaming to a Scroll.' },
  { category:'Recon & Surveillance', rarity:'Uncommon', name:'Tracking Beacon Pack (×6)', price:960, desc:'Tiny adhesive beacons with encrypted location broadcasting.' },
  { category:'Recon & Surveillance', rarity:'Uncommon', name:'Directional Microphone', price:640, desc:'Long-range audio pickup system for surveillance and rescue operations.' },
  { category:'Recon & Surveillance', rarity:'Rare', name:'Atlas Recon Drone', price:9400, desc:'Advanced autonomous reconnaissance drone with thermal, optical, and mapping systems.' },
  { category:'Recon & Surveillance', rarity:'Rare', name:'Grimm Observation Sensor', price:5700, desc:'Specialized stationary sensor for recording Grimm movement and behavior over long periods.' },

  { category:'Camping & Survival', rarity:'Common', name:'Portable Water Filter', price:75, desc:'Compact pump filter capable of treating contaminated wilderness water.' },
  { category:'Camping & Survival', rarity:'Common', name:'Firestarter & Stove Kit', price:85, desc:'Compact camp stove, fuel starter, and windproof ignition kit.' },
  { category:'Camping & Survival', rarity:'Common', name:'Four-Season Sleeping Roll', price:130, desc:'Insulated and waterproof sleeping system for harsh field conditions.' },
  { category:'Camping & Survival', rarity:'Common', name:'Emergency Climbing Rope — 50m', price:105, desc:'High-strength lightweight rope rated for rescue and climbing.' },
  { category:'Camping & Survival', rarity:'Uncommon', name:'Grimm-Safe Scent Masking Kit', price:390, desc:'Chemical and botanical odor masking intended to reduce a camp’s scent signature.' },
  { category:'Camping & Survival', rarity:'Uncommon', name:'Portable Solar Charger', price:460, desc:'Foldable charger for Scrolls, lights, sensors, and field electronics.' },
  { category:'Camping & Survival', rarity:'Rare', name:'Huntsman Mobile Shelter', price:2800, desc:'Armored deployable shelter for four people with basic filtration and equipment charging.' },

  { category:'Food & Lodging', rarity:'Common', name:'Cheap Inn Room — 1 Night', price:35, desc:'Basic private room in a low-cost inn or roadside lodge.' },
  { category:'Food & Lodging', rarity:'Common', name:'Comfortable Inn Room — 1 Night', price:90, desc:'Clean private room, secure storage, and a hot meal.' },
  { category:'Food & Lodging', rarity:'Uncommon', name:'Luxury Hotel Room — 1 Night', price:380, desc:'High-end kingdom lodging with private facilities, security, and room service.' },
  { category:'Food & Lodging', rarity:'Common', name:'Street Food Meal', price:9, desc:'Hot local meal from a market stall or food cart.' },
  { category:'Food & Lodging', rarity:'Common', name:'Restaurant Meal', price:28, desc:'Good sit-down meal at a reputable local restaurant.' },
  { category:'Food & Lodging', rarity:'Uncommon', name:'Private Banquet Reservation', price:650, desc:'Reserved dining space and catered meal for a Huntsman team or formal meeting.' },

  { category:'Vehicles & Upgrades', rarity:'Uncommon', name:'Motorcycle Armor Package', price:1200, desc:'Reinforced plating and frame modifications for a motorcycle.' },
  { category:'Vehicles & Upgrades', rarity:'Uncommon', name:'Off-Road Bike Conversion', price:1700, desc:'Suspension, tires, and gearing modifications for wilderness travel.' },
  { category:'Vehicles & Upgrades', rarity:'Uncommon', name:'Vehicle Weapon Mount', price:2300, desc:'Reinforced universal mount for legally authorized vehicle-mounted weaponry.' },
  { category:'Vehicles & Upgrades', rarity:'Rare', name:'Dust Turbo System', price:6800, desc:'Dust-powered acceleration system for compatible vehicles.' },
  { category:'Vehicles & Upgrades', rarity:'Rare', name:'Armored Huntsman Motorcycle', price:18500, desc:'Purpose-built combat motorcycle with reinforced frame, storage, and Dust-compatible systems.' },
  { category:'Vehicles & Upgrades', rarity:'Rare', name:'Civilian Utility Truck', price:26000, desc:'Reliable four-wheel utility vehicle with cargo space suitable for a Huntsman team.' },

  { category:'Training & Education', rarity:'Common', name:'Weapons Maintenance Course', price:180, desc:'Practical class covering basic repair, cleaning, and emergency field maintenance.' },
  { category:'Training & Education', rarity:'Common', name:'Wilderness Survival Course', price:210, desc:'Two-day introductory training in navigation, shelter, food, and emergency signaling.' },
  { category:'Training & Education', rarity:'Uncommon', name:'Advanced Grimm Anatomy Seminar', price:480, desc:'Specialized lecture and practical workshop on Grimm weak points and behavioral patterns.' },
  { category:'Training & Education', rarity:'Uncommon', name:'Dust Handling Certification', price:620, desc:'Professional safety certification for transporting and using industrial quantities of Dust.' },
  { category:'Training & Education', rarity:'Uncommon', name:'Advanced Weapon Sparring Session', price:380, desc:'Private combat session with an experienced Huntsman instructor.' },
  { category:'Training & Education', rarity:'Rare', name:'Specialist Huntsman Mentorship — 1 Week', price:4200, desc:'Intensive one-week private training arrangement with a veteran Huntsman or specialist.' },

  { category:'Services', rarity:'Common', name:'Weapon Cleaning & Inspection', price:85, desc:'Professional cleaning and inspection of a single weapon.' },
  { category:'Services', rarity:'Common', name:'Armor Repair', price:180, desc:'Basic repair of cracked plates, torn straps, and damaged protective clothing.' },
  { category:'Services', rarity:'Uncommon', name:'Dust Weapon Calibration', price:480, desc:'Professional calibration of Dust channels, chambers, and control systems.' },
  { category:'Services', rarity:'Uncommon', name:'Private Investigator — 1 Day', price:950, desc:'Licensed investigator hired for surveillance, background research, or locating a person.' },
  { category:'Services', rarity:'Uncommon', name:'Bodyguard Team — 1 Day', price:1800, desc:'Two trained private security personnel for a full day.' },
  { category:'Services', rarity:'Rare', name:'Huntsman Escort Contract', price:5200, desc:'Hire a licensed Huntsman for one dangerous escort mission, subject to availability.' },
  { category:'Services', rarity:'Rare', name:'Emergency Bullhead Extraction', price:11000, desc:'Priority emergency air extraction from a dangerous region, weather and Grimm permitting.' },

  { category:'Black Market', rarity:'Uncommon', name:'Forged Civilian ID', price:1800, desc:'False civilian identification. Quality and legality vary considerably.' },
  { category:'Black Market', rarity:'Uncommon', name:'Unregistered Weapon Serial Rework', price:2400, desc:'Illegal removal or alteration of weapon identification markings.' },
  { category:'Black Market', rarity:'Rare', name:'Stolen Atlas Security Pass', price:7500, desc:'Time-sensitive stolen credentials. Likely to be revoked if detected.' },
  { category:'Black Market', rarity:'Rare', name:'Military Dust Detonator', price:9800, desc:'Restricted remote triggering system designed for high-yield Dust charges.' },
  { category:'Black Market', rarity:'Rare', name:'Aura Signature Scrambler', price:14500, desc:'Experimental device intended to interfere with some Aura-based identity scanners.' },
  { category:'Black Market', rarity:'Rare', name:'Prototype Hard-Light Cloak', price:24000, desc:'Unstable experimental camouflage technology with severe power requirements.' },

  { category:'Collectibles & Personal', rarity:'Common', name:'Custom Team Patch Set', price:60, desc:'Embroidered team insignia patches for jackets, bags, and armor.' },
  { category:'Collectibles & Personal', rarity:'Common', name:'Custom Weapon Charm', price:45, desc:'Small decorative charm mounted to a weapon or Scroll.' },
  { category:'Collectibles & Personal', rarity:'Common', name:'Printed Team Photograph', price:20, desc:'High-quality physical team photograph in a protective sleeve.' },
  { category:'Collectibles & Personal', rarity:'Uncommon', name:'Custom Huntsman Jacket', price:680, desc:'Tailored jacket with team colors, insignia, reinforced seams, and custom pockets.' },
  { category:'Collectibles & Personal', rarity:'Uncommon', name:'Engraved Huntsman Flask', price:140, desc:'Durable engraved metal flask or canteen personalized with a name or team emblem.' },
  { category:'Collectibles & Personal', rarity:'Rare', name:'Master-Crafted Display Weapon', price:4600, desc:'Non-combat collector piece created by a professional weaponsmith to exacting standards.' }
];
