window.RWBY_DEFAULT_SHOP = [
  { category:'Dust — Crystals', rarity:'Common', name:'Fire Dust Crystal', price:1200, desc:'Refined red crystal. Ignites on impact or channels through a weapon. SDC grade, post-embargo pricing.' },
  { category:'Dust — Crystals', rarity:'Common', name:'Ice Dust Crystal', price:900, desc:'Pale blue crystal. Freezes targets and surfaces, forms barriers of ice.' },
  { category:'Dust — Crystals', rarity:'Common', name:'Lightning Dust Crystal', price:850, desc:'Yellow crystal crackling with charge. Arcs between conductive targets.' },
  { category:'Dust — Crystals', rarity:'Common', name:'Wind Dust Crystal', price:730, desc:'Green crystal. Releases concussive gusts, propels gliding and leaping.' },
  { category:'Dust — Crystals', rarity:'Common', name:'Earth Dust Crystal', price:600, desc:'Brown crystal. Raises stone, hardens ground, shapes cover.' },
  { category:'Dust — Crystals', rarity:'Rare', name:'Gravity Dust Crystal', price:14000, desc:'Rare violet crystal. Alters local gravity for floating platforms or crushing slams. Severe shortage since the rail line attacks.' },
  { category:'Dust — Crystals', rarity:'Rare', name:'Hard-Light Dust Crystal', price:16500, desc:'Rare prismatic crystal. Projects solid-light constructs and shields. Atlas-restricted, black-market priced.' },

  { category:'Dust — Vials & Powder', rarity:'Common', name:'Fire Dust Vial (powdered)', price:180, desc:'Loose red Dust for cartridge loading or pouches. Cheaper per use than crystal, less stable.' },
  { category:'Dust — Vials & Powder', rarity:'Common', name:'Ice Dust Vial (powdered)', price:180, desc:'Loose blue Dust. Common ammunition infusion.' },
  { category:'Dust — Vials & Powder', rarity:'Common', name:'Lightning Dust Vial (powdered)', price:190, desc:'Loose yellow Dust. Standard for ranged weapon charging.' },
  { category:'Dust — Vials & Powder', rarity:'Common', name:'Wind Dust Vial (powdered)', price:170, desc:'Loose green Dust. Mobility and knockback rounds.' },
  { category:'Dust — Vials & Powder', rarity:'Common', name:'Earth Dust Vial (powdered)', price:160, desc:'Loose brown Dust. Defensive and terrain rounds.' },
  { category:'Dust — Vials & Powder', rarity:'Rare', name:'Gravity Dust Vial (powdered)', price:520, desc:'Loose violet Dust. Scarce; rationed by most reputable shops.' },
  { category:'Dust — Vials & Powder', rarity:'Common', name:'Mixed Dust Pouch (assorted)', price:220, desc:'A pouch of mismatched powdered Dust. Unreliable potency, budget option.' },

  { category:'Dust — Ammunition', rarity:'Common', name:'Dust Cartridges, Standard (×30)', price:120, desc:'Pre-loaded rounds infused with elemental Dust. Specify element on purchase.' },
  { category:'Dust — Ammunition', rarity:'Common', name:'Dust Cartridges, Heavy (×15)', price:160, desc:'High-caliber Dust rounds for cannon-class weapons.' },
  { category:'Dust — Ammunition', rarity:'Common', name:'Dust Shells, Shotgun (×20)', price:140, desc:'Scattershot Dust shells. Popular for melee-shift weapons.' },
  { category:'Dust — Ammunition', rarity:'Common', name:'Dust Rounds, Sniper (×10)', price:200, desc:'Precision-cut Dust rounds with stabilized burn.' },

  { category:'Weapons — Melee', rarity:'Common', name:'Combat Knife', price:80, desc:'1d4 piercing/slashing. Light, concealable, throwable.' },
  { category:'Weapons — Melee', rarity:'Common', name:'Short Sword', price:180, desc:'1d6 slashing. Reliable Huntsman trainee sidearm.' },
  { category:'Weapons — Melee', rarity:'Common', name:'Longsword', price:300, desc:'1d8 slashing, two-handed 1d10. Standard versatile blade.' },
  { category:'Weapons — Melee', rarity:'Common', name:'Greatsword', price:500, desc:'2d6 slashing, heavy, two-handed. Favored by power fighters.' },
  { category:'Weapons — Melee', rarity:'Common', name:'War Axe', price:340, desc:'1d8 slashing, brutal on a critical hit.' },
  { category:'Weapons — Melee', rarity:'Common', name:'Battle Spear', price:260, desc:'1d8 piercing, reach. Keeps Grimm at distance.' },
  { category:'Weapons — Melee', rarity:'Common', name:'War Hammer', price:420, desc:'2d6 bludgeoning, heavy. Stuns and shatters guard.' },
  { category:'Weapons — Melee', rarity:'Common', name:'Twin Daggers (pair)', price:240, desc:'1d4 each, light, dual-wield. Quick Semblance-paired strikes.' },
  { category:'Weapons — Melee', rarity:'Common', name:'Quarterstaff', price:60, desc:'1d6 bludgeoning, versatile 1d8. Cheap, dependable.' },

  { category:'Weapons — Ranged', rarity:'Common', name:'Light Pistol', price:280, desc:'1d8 piercing, 30/90 ft. Sidearm; chambers Dust cartridges.' },
  { category:'Weapons — Ranged', rarity:'Common', name:'Hunting Rifle', price:520, desc:'1d10 piercing, 80/240 ft. Bread-and-butter Huntsman ranged arm.' },
  { category:'Weapons — Ranged', rarity:'Common', name:'Combat Shotgun', price:480, desc:'2d6 at close range, 30/90 ft. Pairs with shift-weapons.' },
  { category:'Weapons — Ranged', rarity:'Uncommon', name:'Sniper Rifle', price:900, desc:'2d10 piercing, 120/480 ft. High cost, high reach.' },
  { category:'Weapons — Ranged', rarity:'Common', name:'Recurve Bow', price:120, desc:'1d8 piercing, 150/600 ft. Silent; takes Dust-tipped arrows.' },
  { category:'Weapons — Ranged', rarity:'Common', name:'Hand Crossbow', price:160, desc:'1d6 piercing, light, 30/120 ft.' },

  { category:'Weapons — Mecha-Shift', rarity:'Uncommon', name:'Mecha-Shift Frame (blank)', price:1200, desc:'A modular weapon chassis that transforms between two configured forms. Requires a smith to fit your blueprint.' },
  { category:'Weapons — Mecha-Shift', rarity:'Uncommon', name:'Transformation Smithing (service)', price:850, desc:'A weaponsmith adds a second mecha-shift form to a weapon you already own.' },
  { category:'Weapons — Mecha-Shift', rarity:'Uncommon', name:'Dust-Channeling Refit (service)', price:600, desc:'Upgrades a weapon to channel loaded Dust through its strikes or shots.' },

  { category:'Armor', rarity:'Common', name:'Reinforced Clothing', price:120, desc:'+1 AC. Light huntsman garb with woven plating. No stealth penalty.' },
  { category:'Armor', rarity:'Common', name:'Leather Combat Gear', price:200, desc:'Light armor, AC 11 + DEX. Flexible and quiet.' },
  { category:'Armor', rarity:'Common', name:'Studded Huntsman Vest', price:450, desc:'Light armor, AC 12 + DEX. Standard academy issue.' },
  { category:'Armor', rarity:'Common', name:'Chain Shirt', price:500, desc:'Medium armor, AC 13 + DEX (max 2). Worn under clothing.' },
  { category:'Armor', rarity:'Uncommon', name:'Reinforced Breastplate', price:800, desc:'Medium armor, AC 14 + DEX (max 2). Atlas-forged steel.' },
  { category:'Armor', rarity:'Rare', name:'Half-Plate', price:1500, desc:'Medium armor, AC 15 + DEX (max 2). Stealth disadvantage.' },
  { category:'Armor', rarity:'Rare', name:'Full Plate', price:3000, desc:'Heavy armor, AC 18. Stealth disadvantage, STR 15 required.' },
  { category:'Armor', rarity:'Common', name:'Combat Shield', price:150, desc:'+2 AC. Some collapse into a gauntlet for shift-weapon users.' },
  { category:'Armor', rarity:'Uncommon', name:'Dust-Weave Cloak', price:18000, desc:'Resistant to one chosen Dust element; faint shimmer when triggered.' },

  { category:'Tools & Tech', rarity:'Common', name:'Scroll (standard)', price:400, desc:'The handheld communication and info device of Remnant. Calls, maps, Aura readouts, transformation triggers. Networked to the CCT.' },
  { category:'Tools & Tech', rarity:'Uncommon', name:'Scroll (military-grade)', price:1100, desc:'Hardened Atlas Scroll with encrypted comms, deployable holo-display, and Aura-scanner ports.' },
  { category:'Tools & Tech', rarity:'Common', name:'First-Aid Med Kit', price:90, desc:'Bandages, salves, and a stim shot. Stabilizes a downed ally or restores a short rest of HP.' },
  { category:'Tools & Tech', rarity:'Common', name:'Field Surgery Kit', price:260, desc:'Advanced kit; grants advantage on Medicine checks and treats serious wounds.' },
  { category:'Tools & Tech', rarity:'Common', name:'Aura Stabilizer (single-use)', price:3200, desc:'Injector that jump-starts a depleted Aura, restoring a small reserve once per use.' },
  { category:'Tools & Tech', rarity:'Common', name:'Dust Refining Kit', price:3800, desc:'Portable tools to refine raw Dust into usable powder or recharge cartridges.' },
  { category:'Tools & Tech', rarity:'Common', name:'Grappling Hook & Line', price:75, desc:'50 ft line with a Dust-assisted retract. Climb, swing, or pull.' },
  { category:'Tools & Tech', rarity:'Common', name:'Climbing Kit', price:50, desc:'Pitons, harness, and rope for vertical terrain.' },
  { category:'Tools & Tech', rarity:'Common', name:'Survival Pack', price:110, desc:'Bedroll, rations (7 days), tinderbox, mess kit, waterskin, rope.' },
  { category:'Tools & Tech', rarity:'Common', name:'Binoculars (Dust-optic)', price:140, desc:'Long-range optics with low-light Dust enhancement.' },
  { category:'Tools & Tech', rarity:'Common', name:'Holo-Map Projector', price:230, desc:'Projects terrain and tactical overlays from Scroll data.' },
  { category:'Tools & Tech', rarity:'Common', name:'Lockpick Set', price:60, desc:'Quality picks for mechanical and simple electronic locks.' },
  { category:'Tools & Tech', rarity:'Common', name:'Flare Launcher (×6 flares)', price:85, desc:'Signal flares for distress, marking, or a brief blinding flash.' },
  { category:'Tools & Tech', rarity:'Rare', name:'Portable Shield Generator', price:13000, desc:'Deploys a temporary Hard-Light barrier. Atlas tech, limited charges.' },

  { category:'Consumables', rarity:'Common', name:'Healing Tonic', price:1300, desc:'Restores a modest amount of HP when drunk. Bitter, fast-acting.' },
  { category:'Consumables', rarity:'Common', name:'Stim Shot', price:1800, desc:'Temporary surge of speed and resilience for one encounter.' },
  { category:'Consumables', rarity:'Common', name:'Antitoxin Vial', price:6000, desc:'Advantage on saves against poison for one hour.' },
  { category:'Consumables', rarity:'Common', name:'Smoke Pellets (×5)', price:70, desc:'Throwable smoke for cover or escape.' },
  { category:'Consumables', rarity:'Common', name:'Ration Bars (×7)', price:35, desc:'A week of compact field rations.' },
  { category:'Consumables', rarity:'Common', name:'Aura Energy Drink', price:45000, desc:'Minor Aura regen over a short rest. Tastes like burnt sugar.' },

  { category:'Services', rarity:'Common', name:'Weapon Maintenance', price:500, desc:'A smith cleans, sharpens, and tunes one weapon to peak condition.' },
  { category:'Services', rarity:'Common', name:'Armor Repair', price:8000, desc:'Restores damaged armor to full protection.' },
  { category:'Services', rarity:'Common', name:'Dust Recharge (per weapon)', price:9000, desc:'Tops off a weapon\u2019s built-in Dust reservoir.' },
  { category:'Services', rarity:'Common', name:'Bullhead Transport (one-way)', price:3000, desc:'Airship passage to a kingdom or frontier outpost.' },
  { category:'Services', rarity:'Common', name:'Inn Stay (per night)', price:250, desc:'A bed, a hot meal, and a locked door between you and the night.' },
{ category:'Weapons — Melee', rarity:'Uncommon', name:'Chain Scythe', price:780, desc:'1d8 slashing with reach. Collapsible segmented haft; favored by highly mobile Huntsmen.' },
  { category:'Weapons — Melee', rarity:'Uncommon', name:'Dust Edge Saber', price:980, desc:'1d8 slashing. Replaceable Dust channel along the blade can add elemental effects when loaded.' },
  { category:'Weapons — Melee', rarity:'Uncommon', name:'Twin Tonfa Blades', price:720, desc:'Paired defensive blades designed for close-range counters and fast follow-up strikes.' },
  { category:'Weapons — Melee', rarity:'Rare', name:'Vibro-Greatblade', price:4200, desc:'Heavy two-handed blade with a Dust-powered vibration core for breaking armor and Grimm plating.' },

  { category:'Weapons — Ranged', rarity:'Common', name:'Machine Pistol', price:440, desc:'Compact automatic sidearm. High fire rate, short effective range, accepts standard Dust cartridges.' },
  { category:'Weapons — Ranged', rarity:'Uncommon', name:'Burst Carbine', price:880, desc:'Reliable three-round-burst rifle for mid-range Huntsman engagements.' },
  { category:'Weapons — Ranged', rarity:'Uncommon', name:'Heavy Revolver', price:760, desc:'High-caliber sidearm with excellent stopping power. Common among independent Huntsmen.' },
  { category:'Weapons — Ranged', rarity:'Rare', name:'Dust Rail Rifle', price:6200, desc:'Atlas-pattern long rifle that accelerates Dust-infused slugs. Extremely accurate and expensive to maintain.' },
  { category:'Weapons — Ranged', rarity:'Uncommon', name:'Repeating Crossbow', price:620, desc:'Compact repeating bow with magazine-fed bolts; useful where gunfire would attract Grimm.' },

  { category:'Weapons — Mecha-Shift', rarity:'Rare', name:'Advanced Mecha-Shift Core', price:4800, desc:'Precision transformation core supporting three mechanical configurations instead of two.' },
  { category:'Weapons — Mecha-Shift', rarity:'Rare', name:'Integrated Grapple Module', price:2100, desc:'Weapon-mounted retractable grappling system for rapid traversal, pulls, and aerial repositioning.' },
  { category:'Weapons — Mecha-Shift', rarity:'Rare', name:'Recoil Mobility Refit', price:2700, desc:'Reinforces a ranged weapon so recoil can safely be used for movement and airborne direction changes.' },
  { category:'Weapons — Mecha-Shift', rarity:'Rare', name:'Hidden Weapon Conversion', price:3500, desc:'Converts one weapon form into a disguised civilian object or compact carry mode.' },

  { category:'Dust — Ammunition', rarity:'Common', name:'Fire Dust Magazine (×20)', price:220, desc:'Preloaded magazine of incendiary Dust rounds.' },
  { category:'Dust — Ammunition', rarity:'Common', name:'Ice Dust Magazine (×20)', price:220, desc:'Preloaded cryogenic Dust rounds that rapidly chill struck surfaces.' },
  { category:'Dust — Ammunition', rarity:'Common', name:'Lightning Dust Magazine (×20)', price:240, desc:'Electrified Dust rounds useful against machines and conductive targets.' },
  { category:'Dust — Ammunition', rarity:'Uncommon', name:'Gravity Dust Rounds (×10)', price:850, desc:'Specialized rounds that create brief localized gravity distortions on impact.' },
  { category:'Dust — Ammunition', rarity:'Rare', name:'Hard-Light Breach Rounds (×6)', price:1600, desc:'Atlas hard-light projectiles designed to punch through cover before destabilizing.' },
  { category:'Dust — Ammunition', rarity:'Uncommon', name:'Dust-Tipped Arrows (×12)', price:360, desc:'Choose Fire, Ice, Wind, Lightning, or Earth when purchased.' },

  { category:'Armor', rarity:'Uncommon', name:'Huntsman Longcoat', price:720, desc:'Reinforced coat with concealed plates and Dust-resistant lining. Built for mobility and weather protection.' },
  { category:'Armor', rarity:'Uncommon', name:'Faunus Mobility Harness', price:680, desc:'Flexible combat harness designed not to obstruct tails, ears, wings, horns, or other Faunus traits.' },
  { category:'Armor', rarity:'Uncommon', name:'Aura-Conductive Undersuit', price:2200, desc:'Special weave designed to distribute Aura reinforcement more evenly across the body.' },
  { category:'Armor', rarity:'Rare', name:'Atlas Tactical Exoskeleton', price:12500, desc:'Powered support frame for carrying heavy equipment and stabilizing recoil. Requires regular charging.' },
  { category:'Armor', rarity:'Rare', name:'Hard-Light Buckler', price:9800, desc:'Wrist-mounted projector forming a compact Hard-Light shield when activated.' },

  { category:'Tools & Tech', rarity:'Common', name:'Weapon Cleaning Kit', price:55, desc:'Brushes, solvents, oils, micro-tools and sharpening gear for field maintenance.' },
  { category:'Tools & Tech', rarity:'Common', name:'Portable CCT Relay', price:950, desc:'Short-range communication relay for maintaining team contact in weak-signal areas.' },
  { category:'Tools & Tech', rarity:'Uncommon', name:'Aura Scanner', price:1600, desc:'Handheld scanner that estimates Aura reserves and detects abrupt Aura fluctuations.' },
  { category:'Tools & Tech', rarity:'Uncommon', name:'Grimm Motion Sensor', price:1250, desc:'Deployable sensor tuned to large moving biological signatures and Grimm activity.' },
  { category:'Tools & Tech', rarity:'Uncommon', name:'Thermal Monocular', price:780, desc:'Low-light and heat-signature optic that clips to a visor or weapon rail.' },
  { category:'Tools & Tech', rarity:'Uncommon', name:'Encrypted Scroll Module', price:1450, desc:'Adds encrypted team channels and secure file storage to a standard Scroll.' },
  { category:'Tools & Tech', rarity:'Rare', name:'Portable Hard-Light Workbench', price:7600, desc:'Compact projection bench used for weaponsmithing, field repairs, and schematic work.' },
  { category:'Tools & Tech', rarity:'Rare', name:'Micro-Drone Scout', price:5800, desc:'Palm-sized reconnaissance drone with camera, microphone, and short-range Scroll link.' },
  { category:'Tools & Tech', rarity:'Rare', name:'Signal Jammer', price:5200, desc:'Short-range electronic jammer. Illegal in many civilian districts without authorization.' },

  { category:'Field Gear', rarity:'Common', name:'Huntsman Field Pack', price:180, desc:'Durable mission pack with reinforced straps, modular pouches, hydration bladder, and weapon attachment points.' },
  { category:'Field Gear', rarity:'Common', name:'Cold-Weather Kit', price:140, desc:'Insulated layers, thermal blanket, hand warmers, snow goggles and emergency heat packs.' },
  { category:'Field Gear', rarity:'Common', name:'Desert Survival Kit', price:160, desc:'Shade cloth, water purification tablets, cooling wrap, goggles and compact electrolyte packs.' },
  { category:'Field Gear', rarity:'Common', name:'Urban Infiltration Kit', price:220, desc:'Compact pry tools, glass cutter, cable launcher, blackout cloth and disposable disguises.' },
  { category:'Field Gear', rarity:'Uncommon', name:'Climbing Grapnel Launcher', price:520, desc:'Compressed-gas launcher with reinforced line for rapid rooftop or cliff access.' },
  { category:'Field Gear', rarity:'Uncommon', name:'Emergency Beacon', price:300, desc:'Long-range distress beacon with flashing locator and encoded Scroll identifier.' },
  { category:'Field Gear', rarity:'Uncommon', name:'Portable Tent — Huntsman Grade', price:360, desc:'Lightweight reinforced shelter resistant to severe weather and minor Grimm scratches.' },

  { category:'Consumables', rarity:'Common', name:'Combat Ration Pack', price:18, desc:'One day of high-calorie field food designed for Huntsmen on extended missions.' },
  { category:'Consumables', rarity:'Common', name:'Electrolyte Recovery Pack', price:35, desc:'Powdered hydration mix for recovery after long travel or combat.' },
  { category:'Consumables', rarity:'Common', name:'Burn Treatment Foam', price:90, desc:'Rapid-cooling medical foam for fire and Dust burns.' },
  { category:'Consumables', rarity:'Common', name:'Coagulant Spray', price:110, desc:'Emergency wound sealant used to control heavy bleeding until proper treatment is available.' },
  { category:'Consumables', rarity:'Uncommon', name:'Aura Recovery Ampoule', price:2400, desc:'Single-use stimulant formulated to improve Aura recovery during a rest. Overuse is discouraged.' },
  { category:'Consumables', rarity:'Uncommon', name:'Focus Suppressant', price:750, desc:'Short-term medication used by some Huntsmen to steady severe adrenaline shakes after combat.' },

  { category:'Academy & Training', rarity:'Common', name:'Beacon Training Pass', price:120, desc:'Access to academy sparring rooms, basic targets, and standard training equipment for one session.' },
  { category:'Academy & Training', rarity:'Common', name:'Dust Practice Pack', price:95, desc:'Low-yield training Dust cartridges intended for controlled practice.' },
  { category:'Academy & Training', rarity:'Uncommon', name:'Combat Simulation Session', price:350, desc:'One advanced training-room simulation with configurable Grimm and terrain scenarios.' },
  { category:'Academy & Training', rarity:'Uncommon', name:'Weaponsmith Consultation', price:260, desc:'One hour with a professional weaponsmith to review a weapon concept, fault, or upgrade path.' },
  { category:'Academy & Training', rarity:'Uncommon', name:'Semblance Control Session', price:400, desc:'Supervised session focused on control, efficiency, and safe limits rather than raw power.' },

  { category:'Travel & Vehicles', rarity:'Common', name:'Inter-City Rail Ticket', price:180, desc:'Standard civilian rail passage where service remains available.' },
  { category:'Travel & Vehicles', rarity:'Common', name:'Motorcycle Rental — 1 Day', price:420, desc:'Civilian motorcycle rental with basic insurance and fuel.' },
  { category:'Travel & Vehicles', rarity:'Uncommon', name:'Huntsman Bike Rental — 1 Day', price:750, desc:'Reinforced off-road motorcycle equipped for rough terrain and weapon storage.' },
  { category:'Travel & Vehicles', rarity:'Uncommon', name:'Bullhead Charter — Local', price:2200, desc:'Private Bullhead transport for a small team within the same kingdom.' },
  { category:'Travel & Vehicles', rarity:'Rare', name:'Bullhead Charter — Long Range', price:7800, desc:'Long-range charter with pilot, fuel, and limited cargo capacity.' },

  { category:'Services', rarity:'Uncommon', name:'Custom Weapon Engraving', price:280, desc:'Professional engraving, insignia work, team markings, or personalization.' },
  { category:'Services', rarity:'Uncommon', name:'Weapon Balance Tuning', price:650, desc:'Precision adjustment of grip, recoil, weight distribution, and transformation timing.' },
  { category:'Services', rarity:'Uncommon', name:'Scroll Data Recovery', price:900, desc:'Technical service attempting to recover damaged or deleted data from a Scroll.' },
  { category:'Services', rarity:'Rare', name:'Full Mecha-Shift Rebuild', price:7200, desc:'Complete overhaul of a damaged or outdated transforming weapon mechanism.' },

  { category:'Black Market', rarity:'Uncommon', name:'Unregistered Scroll', price:2300, desc:'A Scroll with falsified ownership records. Possession may be illegal depending on jurisdiction.' },
  { category:'Black Market', rarity:'Rare', name:'Atlas Access Spoofer', price:8400, desc:'Illegal device intended to imitate low-level Atlas credentials. Reliability is questionable.' },
  { category:'Black Market', rarity:'Rare', name:'Restricted Dust Case', price:12500, desc:'Military-grade sealed case containing assorted high-output Dust charges. Highly regulated.' },
  { category:'Black Market', rarity:'Rare', name:'Prototype Aura Capacitor', price:18500, desc:'Experimental device intended to temporarily store Aura-derived energy. Unstable and unsupported.' }
];
